language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp6-7_lab_List_Arraylist
  - make -j
  - ./test/MP_6_7_TESTS
notifications:
  email: false
